import argparse
import ast
import hashlib
import json
from pathlib import Path
import tarfile
import io
import gzip

ROOT = Path(__file__).resolve().parents[1]
MODULES = ['params', 'state', 'economy', 'routing', 'market', 'planner']


def build(output, parameters=None):
    parameters = parameters or {}
    from agent.params import DEFAULTS
    unknown = set(parameters) - set(DEFAULTS)
    if unknown:
        raise ValueError(f'Unknown parameters: {unknown}')
    chunks = ['# Generated by submission.build; standard library only.\n']
    for name in MODULES:
        path = ROOT / 'agent' / f'{name}.py'
        tree = ast.parse(path.read_text())
        tree.body = [node for node in tree.body if not (isinstance(node, ast.ImportFrom) and node.level)]
        chunks.append(ast.unparse(tree))
    chunks.append('PARAMETERS = ' + repr(parameters))
    # Must be the final callable: Kaggle's file loader selects the last callable.
    chunks.append('def agent(observation, configuration=None):\n    return policy(observation, configuration, PARAMETERS)\n')
    source = '\n\n'.join(chunks) + '\n'
    compile(source, 'main.py', 'exec')
    path = Path(output)
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() != source:
        raise FileExistsError(f'Refusing to overwrite a different artifact: {path}')
    path.write_text(source)
    digest = hashlib.sha256(source.encode()).hexdigest()
    manifest = {'sha256': digest, 'parameters': {**DEFAULTS, **parameters},
                'source_hashes': {m: hashlib.sha256((ROOT / 'agent' / f'{m}.py').read_bytes()).hexdigest() for m in MODULES}}
    path.with_suffix('.manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
    # Reproducible gzip/tar metadata; main.py at the archive root.
    buffer = io.BytesIO()
    with tarfile.open(fileobj=buffer, mode='w') as archive:
        member = tarfile.TarInfo('main.py')
        member.size = len(source.encode())
        member.mode = 0o644
        archive.addfile(member, io.BytesIO(source.encode()))
    path.with_suffix('.tar.gz').write_bytes(gzip.compress(buffer.getvalue(), mtime=0))
    return manifest


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--output', default='submission/dist/main.py')
    parser.add_argument('--params', help='JSON file with parameter overrides')
    args = parser.parse_args()
    print(json.dumps(build(args.output, json.loads(Path(args.params).read_text()) if args.params else None), indent=2))


if __name__ == '__main__':
    main()
