# Generated by submission.build; standard library only.


DEFAULTS = {'max_hands': 8, 'cash_reserve': 250, 'travel_cost': 3.0, 'opponent_weight': 0.8, 'adaptive': True, 'only_crop': None, 'max_quadrants': 2, 'expand_day': 7, 'animal_target': 0, 'animal_type': 'GOOSE', 'water_daily': True, 'plant_until_hour': 18, 'sell_fraction': 1.0}

from dataclasses import dataclass

@dataclass
class State:
    obs: dict
    config: dict

    @property
    def me(self):
        return self.obs['farms'][self.obs['player']]

    @property
    def opponent(self):
        return self.obs['farms'][1 - self.obs['player']]

    @property
    def private(self):
        return self.obs['private']

    @property
    def day(self):
        return self.obs['day']

    @property
    def hour(self):
        return self.obs['hour']

    @property
    def turns_per_day(self):
        return self.config.get('turnsPerDay', 24)

    @property
    def step(self):
        return self.obs.get('step', self.day * self.turns_per_day + self.hour)

    @property
    def turns_left(self):
        return self.config.get('episodeSteps', 720) - 1 - self.step

    @property
    def days_left(self):
        return self.turns_left / self.turns_per_day

    @property
    def positions(self):
        return [self.me['farmer'], *self.me['hands']]

    @property
    def size(self):
        return len(self.me['tiles'])

    def tiles(self, opponent=False):
        farm = self.opponent if opponent else self.me
        return [(x, y, tile) for y, row in enumerate(farm['tiles']) for x, tile in enumerate(row) if tile != 'LOCKED']

"""Finite-season estimates; forecasts are hypotheses, never hidden observations."""
import math
CROPS = {'WHEAT': (10, 2, 4, 4, 5), 'CARROT': (20, 2, 3, 3, 4), 'TOMATO': (50, 8, 11, 4, 12), 'STRAWBERRY': (100, 10, 16, 4, 17), 'MELON': (80, 10, 10, 6, 11)}
ANIMALS = {'GOOSE': (300, 'COOP', 'EGG', 4, 1), 'COW': (400, 'PASTURE', 'MILK', 8, 2), 'SHEEP': (500, 'PASTURE', 'WOOL', 6, 3)}
CURVES = {'WHEAT': (25, 400, 'sqrt', 0.8, 'log', 0.2), 'CARROT': (35, 450, 'hinge', 1.0, 'sqrt', 0.7), 'TOMATO': (60, 200, 'hinge', 0.4, 'sqrt', 0.6), 'STRAWBERRY': (120, 100, 'sqrt', 0.7, 'linear', 1.6), 'MELON': (250, 300, 'log', 0.2, 'sq', 3.6), 'EGG': (50, 332, 'hinge', 0.4, 'log', 0.2), 'MILK': (160, 122, 'sqrt', 0.6, 'linear', 1.6), 'WOOL': (200, 105, 'log', 0.2, 'sq', 3.2), 'FERTILIZER': (100, 200, 'linear', 0.4, 'linear', 0.4)}
SHOPS = {'BAKERY': ('EGG', 'WHEAT'), 'PIZZA_SHOP': ('MILK', 'TOMATO', 'WHEAT'), 'BRUNCH_SPOT': ('EGG', 'WHEAT', 'STRAWBERRY'), 'YARN_STORE': ('WOOL',), 'ICE_CREAM_SHOP': ('STRAWBERRY', 'MILK', 'WHEAT'), 'PET_CAFE': ('CARROT',), 'SMOOTHIE_SHOP': ('STRAWBERRY', 'MILK'), 'FARMERS_MARKET': ('WHEAT', 'CARROT', 'TOMATO', 'STRAWBERRY')}

def shape(name, x, throughput):
    if name == 'sqrt':
        return math.sqrt(x)
    if name == 'log':
        return math.log1p(x)
    if name == 'log10':
        return math.log10(1 + x)
    if name == 'sq':
        return x * x
    if name == 'hinge':
        u = x / throughput
        return u + 8 * max(0, u - 1) ** 2
    return x

def price(item, inventory, overrides=None):
    base, throughput, low, lt, high, ht = CURVES[item]
    p = dict(base=base, T=throughput, I0=10000, below_func=low, below_target=lt, above_func=high, above_target=ht)
    p.update((overrides or {}).get(item, {}))
    delta = inventory - p['I0']
    side = 'above' if delta >= 0 else 'below'
    func, target = (p[side + '_func'], p[side + '_target'])
    move = target * p['base'] * shape(func, abs(delta), p['T']) / shape(func, p['T'], p['T'])
    return max(1, round(p['base'] + (-move if delta >= 0 else move)))

def sale_value(item, count, inventory, overrides=None):
    total = 0
    for _ in range(max(0, int(count))):
        quote = price(item, inventory, overrides)
        total += quote
        if quote > 1:
            inventory += 1
    return total

def daily_demand(state, item):
    if item == 'FERTILIZER':
        return 0
    rate = state.turns_per_day / state.config.get('townCenterSellInterval', 24)
    shop_rate = state.turns_per_day / state.config.get('townShopSellInterval', 4)
    for shop in state.obs['town']['unlocked_shops']:
        products = SHOPS[shop]
        if item in products:
            rate += shop_rate * (2 if len(products) == 1 else 1)
    return rate

def crop_scores(state, params, planned=None):
    counts = {c: 0 for c in CROPS}
    for _, _, tile in state.tiles():
        if isinstance(tile, dict) and tile.get('crop') in counts:
            counts[tile['crop']] += 1
    opponent = dict.fromkeys(CROPS, 0)
    for _, _, tile in state.tiles(opponent=True):
        if isinstance(tile, dict) and tile.get('crop') in opponent:
            opponent[tile['crop']] += 1
    scores = {}
    for crop, (seed, first, peak, quantity, occupancy) in CROPS.items():
        if state.days_left < first + 1:
            continue
        if params.get('only_crop') and crop != params['only_crop']:
            continue
        own = counts[crop] + (planned or {}).get(crop, 0)
        other = opponent[crop] * params['opponent_weight']
        demand = daily_demand(state, crop) if params['adaptive'] else 1
        inv = state.obs['market']['inventory'][crop]
        forecast = inv + (own + other) * quantity - demand * min(peak, state.days_left)
        revenue = sale_value(crop, quantity, forecast, state.config.get('marketParams'))
        scores[crop] = (revenue - seed) / (occupancy + params['travel_cost'])
    return scores

def distance(a, b):
    return abs(a[0] - b[0]) + abs(a[1] - b[1])

def move_towards(pos, target):
    x, y = pos
    tx, ty = target
    if x < tx:
        return ['EAST']
    if x > tx:
        return ['WEST']
    if y < ty:
        return ['SOUTH']
    if y > ty:
        return ['NORTH']
    return ['PASS']

def shed_tiles(size):
    h = size // 2
    return [(h - 1, h - 1), (h, h - 1), (h - 1, h), (h, h)]

def nearest_shed(pos, size):
    return min(shed_tiles(size), key=lambda p: distance(pos, p))

def policy(observation, configuration=None, parameters=None):
    p = {**DEFAULTS, **(parameters or {})}
    s = State(observation, configuration or {})
    tiles = s.tiles()
    prices = observation['market']['prices']
    inventories = s.private['inventories']
    shed = dict(s.private['shed'])
    seeds = dict(s.private['seeds'])
    scores = crop_scores(s, p)
    best_crop = max(scores, key=scores.get) if scores else None
    animals = [(x, y, t) for x, y, t in tiles if isinstance(t, dict) and 'animal' in t]
    structures = [(x, y, t) for x, y, t in tiles if isinstance(t, dict) and t.get('kind') in ('COOP', 'PASTURE')]
    animal_type = p['animal_type']
    animal_cost, structure, _, _, _ = ANIMALS[animal_type]
    want_animals = p['animal_target'] if s.days_left > 10 else len(animals)
    jobs = []
    plantable = []
    for x, y, t in tiles:
        pos = (x, y)
        if t is None:
            plantable.append(pos)
            continue
        if t.get('kind') == 'WEED':
            if best_crop and s.hour < p['plant_until_hour']:
                jobs.append((pos, ['DIG'], 14.0, None))
        elif t.get('kind') == 'PLANT':
            crop = t['crop']
            _, first, peak, _, _ = CROPS[crop]
            age = s.day - t['planted_day']
            value = prices[crop] * t.get('yield_units', 0)
            ongoing = crop in ('TOMATO', 'STRAWBERRY')
            endgame = s.turns_left <= s.turns_per_day
            ripe = age >= first and t.get('yield_units', 0) > 0
            harvest = ripe and (ongoing or age >= peak or endgame)
            needs_water = not t['watered_today'] and (p['water_daily'] or t['consecutive_unwatered'] >= 1 or (not ongoing and age >= (peak + 1) // 2))
            if harvest and (not ongoing) and (not endgame) and needs_water:
                jobs.append((pos, ['WATER'], 120 + value * 0.1, None))
            elif harvest:
                jobs.append((pos, ['HARVEST'], 90 + value * 0.3, None))
            elif needs_water and s.turns_left > s.turns_per_day - s.hour:
                urgent = t['consecutive_unwatered'] >= 1
                jobs.append((pos, ['WATER'], 65 + 75 * urgent + s.hour * 3, None))
        elif 'animal' in t:
            if not t['fed_today'] and s.days_left > 1:
                jobs.append((pos, ['FEED'], 160 + 50 * t['consecutive_unfed'], 'WHEAT'))
            if t.get('yield_units', 0):
                product = ANIMALS[t['animal']][2]
                jobs.append((pos, ['HARVEST'], 75 + prices[product] * t['yield_units'] * 0.3, None))
            if t.get('fertilizer_available'):
                jobs.append((pos, ['COLLECT_FERTILIZER'], 30 + prices['FERTILIZER'] * 0.3, None))
            if t['fed_today'] and (not t['cared_today']) and (s.days_left > 2):
                jobs.append((pos, ['CARE'], 45.0, None))
        elif t.get('kind') == structure and len(animals) < want_animals:
            jobs.append((pos, ['PLACE', animal_type], 130.0, animal_type))
    plantable.sort(key=lambda pos: (distance(pos, nearest_shed(pos, s.size)), pos))
    to_build = max(0, want_animals - len(structures))
    for pos in plantable:
        if to_build and s.hour < 15:
            jobs.append((pos, ['BUILD_' + structure], 65.0, None))
            to_build -= 1
        elif best_crop and scores[best_crop] > 0 and (s.hour < p['plant_until_hour']):
            jobs.append((pos, ['PLANT', best_crop], 20 + min(40, scores[best_crop]), None))
    used = set()
    unit_actions = []
    planned_crops = {}
    for index, position in enumerate(s.positions):
        inv = inventories[index]
        target_shed = nearest_shed(position, s.size)
        home_distance = distance(position, target_shed)
        total_inv = sum(inv.values())
        must_drop = total_inv and (s.turns_left <= home_distance + 4 or total_inv >= 15)
        if must_drop:
            unit_actions.append(['DROP'] if home_distance == 0 else move_towards(position, target_shed))
            continue
        ranked = []
        for j, (target, action, value, required) in enumerate(jobs):
            if j in used:
                continue
            travel = distance(position, target)
            if action[0] == 'PLANT':
                if seeds.get(action[1], 0) <= 0:
                    continue
                if s.hour + travel + 2 >= s.turns_per_day:
                    continue
            if action[0] in ('HARVEST', 'COLLECT_FERTILIZER'):
                delivery = distance(target, nearest_shed(target, s.size))
                if travel + delivery + 2 >= s.turns_left:
                    continue
            if travel >= s.turns_per_day - s.hour:
                continue
            if required and (not inv.get(required, 0)):
                if not shed.get(required, 0):
                    continue
                travel = home_distance + distance(target_shed, target) + 1
            ranked.append((value / (1 + travel * 0.65), -j, j))
        if not ranked:
            unit_actions.append(['DROP'] if total_inv and home_distance == 0 else ['PASS'])
            continue
        _, _, chosen = max(ranked)
        target, action, _, required = jobs[chosen]
        used.add(chosen)
        if required and (not inv.get(required, 0)):
            if home_distance:
                result = move_towards(position, target_shed)
            else:
                amount = min(shed[required], 4 if required == 'WHEAT' else 1)
                result = ['PICKUP', required, amount]
                shed[required] -= amount
        elif distance(position, target):
            result = move_towards(position, target)
        else:
            result = list(action)
            if action[0] == 'PLANT':
                seeds[action[1]] -= 1
                planned_crops[action[1]] = planned_crops.get(action[1], 0) + 1
        unit_actions.append(result)
    orders = []
    cash = s.me['money']
    reserve_wheat = len(animals) * 2 if s.days_left > 1 else 0
    for item, amount in s.private['shed'].items():
        if item not in prices:
            continue
        amount -= reserve_wheat if item == 'WHEAT' else 0
        amount = max(0, amount)
        if amount:
            count = amount if s.days_left < 2 else max(1, int(amount * p['sell_fraction']))
            orders.append(['SELL', item, count])
    limit = s.config.get('maxMarketOrdersPerTurn', 10)

    def buy(order, cost):
        nonlocal cash
        if len(orders) < limit and cost <= max(0, cash - p['cash_reserve']):
            orders.append(order)
            cash -= cost
            return True
        return False
    busy = len(jobs)
    desired_hands = min(p['max_hands'], max(0, (busy + 2) // 3))
    if s.hour < 4 and s.turns_left > 12:
        a, b = (1, 1)
        for n in range(desired_hands):
            cost = a * s.config.get('farmHandCostMult', 1)
            if n >= s.me['hires_today']:
                buy(['HIRE'], cost)
            a, b = (b, a + b)
    if best_crop:
        needed = max(0, min(12, len(plantable)) - seeds.get(best_crop, 0))
        if needed:
            buy(['BUY_SEED', best_crop, needed], needed * CROPS[best_crop][0])
    supply_animals = sum((i.get(animal_type, 0) for i in inventories)) + s.private['shed'].get(animal_type, 0)
    if len(animals) + supply_animals < want_animals:
        buy(['BUY_ANIMAL', animal_type, 1], animal_cost)
    wheat_total = s.private['shed'].get('WHEAT', 0) + sum((i.get('WHEAT', 0) for i in inventories))
    if wheat_total < reserve_wheat:
        count = reserve_wheat - wheat_total
        inv = observation['market']['inventory']['WHEAT']
        cost = sum((price('WHEAT', inv - k - 1, s.config.get('marketParams')) for k in range(count)))
        buy(['BUY_PRODUCT', 'WHEAT', count], cost)
    quadrants = len(s.me['unlocked_quadrants'])
    occupied = sum((t is not None for _, _, t in tiles))
    if quadrants < p['max_quadrants'] and s.day >= p['expand_day'] and (s.days_left > 10) and (occupied >= len(tiles) * 0.75):
        buy(['BUY_LAND'], (1000, 2000, 4000)[quadrants - 1])
    return {'farmer': unit_actions[0], 'hands': unit_actions[1:], 'market': orders[:limit]}

PARAMETERS = {}

def agent(observation, configuration=None):
    return policy(observation, configuration, PARAMETERS)

