import hashlib

from arena.agents import agent_hash, load_agent


def write_bundle(directory, helper="VALUE = 1\n"):
    directory.mkdir()
    (directory / 'main.py').write_text(
        "from pathlib import Path\n"
        "VALUE = (Path(__file__).parent / 'helper.py').read_text()\n"
        "def agent(observation, configuration=None):\n"
        "    return {'farmer': ['PASS'], 'market': []}\n"
    )
    (directory / 'helper.py').write_text(helper)
    return directory / 'main.py'


def test_bundle_hash_binds_sibling_runtime_inputs(tmp_path):
    first = write_bundle(tmp_path / 'first', "VALUE = 1\n")
    second = write_bundle(tmp_path / 'second', "VALUE = 2\n")
    assert first.read_bytes() == second.read_bytes()
    assert agent_hash(str(first)) != agent_hash(str(second))


def test_bundle_hash_ignores_packaging_manifest_and_python_cache(tmp_path):
    entrypoint = write_bundle(tmp_path / 'bundle')
    expected = agent_hash(str(entrypoint))
    (entrypoint.parent / 'main.tar.gz').write_bytes(b'generated archive')
    (entrypoint.parent / 'main.manifest.json').write_text('{"generated": true}')
    cache = entrypoint.parent / '__pycache__'
    cache.mkdir()
    (cache / 'helper.cpython-312.pyc').write_bytes(b'generated bytecode')
    assert agent_hash(str(entrypoint)) == expected


def test_standalone_agents_keep_their_file_content_hash(tmp_path):
    standalone = tmp_path / 'replay-opponent.py'
    standalone.write_bytes(b'one agent among unrelated siblings')
    (tmp_path / 'another-opponent.py').write_bytes(b'must not enter its identity')
    assert agent_hash(str(standalone)) == hashlib.sha256(standalone.read_bytes()).hexdigest()


def test_loaded_agent_is_stamped_with_the_effective_bundle_hash(tmp_path):
    entrypoint = write_bundle(tmp_path / 'bundle')
    function = load_agent(str(entrypoint))
    assert function.__arena_sha256__ == agent_hash(str(entrypoint))


def test_bundle_identity_is_bound_before_import_time_code_can_rewrite_it(tmp_path):
    entrypoint = write_bundle(tmp_path / 'bundle')
    entrypoint.write_text(
        "from pathlib import Path\n"
        "(Path(__file__).parent / 'helper.py').write_text('rewritten')\n"
        "def agent(observation, configuration=None):\n"
        "    return {'farmer': ['PASS'], 'market': []}\n"
    )
    before = agent_hash(str(entrypoint))
    function = load_agent(str(entrypoint))
    assert function.__arena_sha256__ == before
    assert agent_hash(str(entrypoint)) != before
